### ISSUE TITLE
Redesign the mini-dashboard

### ISSUE THREAD

**Issue by qdequele** [meilisearch/design-team#1]
# Todo

- [x]  Definir la liste des composants à afficher
- [x]  Faire un draft/ wireframe (1/2 journée)
- [x]  Mettre en page les résultats .json/mode joli (1/2 journée)
- [x]  Faire le mode Advanced (en dessous de la search bar) + Designer l'API key (1/2 journée)
- [x]  Retours et modification après call team core (1 jour)
- [x]  Final tuning (1 jour)

A simple interface with:

- The search bar with the response time and the numbers of candidates
- An optional input for the API Key (+ text)
- The search results, pretty view or json view with a switch
- The facets results with the facet count
- An optional input for manual filters (advanced mode)
- No pagination, load more result (button)
- liste des liens utiles (github/documentation)
