### ISSUE TITLE
Write the Design Principles

### ISSUE THREAD

**Issue by qdequele** [meilisearch/design-team#18]
# Context
Now that the design team is composed of 2 designers, we need clear design principles to follow

# Goal
This issue aims to define design principles for the SaaS, that can also be used for design in general.

# Ressources
[Workshop on Figjam
](https://www.figma.com/file/q4w24pHKTCAaFmhwOkf77v/Design-principles-workshop)
[design principles posters](https://www.figma.com/file/nIHCH5pQKsmIQD5hzQ9TrG/Design-Principles?node-id=108%3A5)
[design principles on notion](https://www.notion.so/meilisearch/Design-principles-6edc44ef96854c38b244109cb267f591)

# Todo
- [x] Create workshop template
- [x] Have a design principles workshop with 6 persons 
- [x] Find the right phrasing for the principles discovered during the workshop
- [x] Create in-brand visuals to explain and expose them @lpinot 
- [x] create documentation on notion

**Comment by chayaline** [comment]
Workshop's results, here are our design principles:
⚠️ the phrasing is not the final one, if you have ideas to improve them, feel free to make suggestions!

- **Intuitive**: Our design should be self-explanatory and explicit. Intuitive design can be invisible. Our user should should always know what to do and feel confident about it.
- **Easy-to-use**: Managing and maintaining a good search system is complex and cost time and energy. Our product should make this task as easy as possible.
- **Flexible**: we want to make fast and quality research available to as many people as possible. Our product should adapt to a large number of use cases and have inclusivity and accessibility as priorities.
- **Developer first**: Tailored for developers, our experience should always make them feel at home. Like our product, our design should feel powerful, fast and relevant. 
- **Memorable**: The experience we provide should always be memorable, exciting and enthusiastic.

**Comment by chayaline** [comment]
![Image](https://user-images.githubusercontent.com/16258667/174836283-6606f3c1-74ef-492e-99e6-5f8e8e947111.png)
