### ISSUE TITLE
Organize the Figma files

### ISSUE THREAD

**Issue by qdequele** [meilisearch/design-team#19]
# Context
With the arrival of @chayaline, we decided to rework the way we organize the information on Figma. In her previous job, @chayaline set up processes and organizations to facilitate work between several designers and developers. 

# Goal
This issue aims to find a file structure for Figma. 

# Ressources
[Figjam whiteboard researches
](https://www.figma.com/file/wlqXmbD53O0px7a2TWkWJV/Figma-mapping?node-id=0%3A1)
[File map and explanations
](https://www.notion.so/meilisearch/How-to-use-Figma-124d3d5a9a774db9a6f52d7f1ca4e06a)
# Todo
- [x] Expose the possible organizations
- [x] Choose one organization with @lpinot
- [x] Apply the new organization 
- [x] define and create a file template (to be used after the Beta release)
- [ ] define naming conventions
- [ ] define processes
- [ ] list the needs in terms of covers and design helpers
