### ISSUE TITLE
Implement the new mini-dashboard

### ISSUE THREAD

**Issue by qdequele** [meilisearch/design-team#2]
# Todo

- [x]  Créer la CI pour faire la release (1 j) → 1,5j
- [x]  Trouver une solution pour faire un build avec un seul fichier de chaque type (html / css / js) ? Si pas d'autre solution côté Core
- [x]  Trouver un moyen de servir plusieurs fichiers static dans MeiliSearch @Quentin de Quelen ([actix-web-static-files](https://crates.io/crates/actix-web-static-files))
- [x]  Mettre en place dependabot et bors (0,5 j) -> 0,5j
- [x]  Mettre en place les outils de base (prettier, eslint, storybook, styled-components themeProvider + globalstyle, absolute imports, ...) (1j) → 1j
- [x]  Regarder l'existant, comment le dashboard est branché avec MeiliSearch + lister les features demandées (0,5 j)
- [x]  Développer les interfaces sans le design (3 j) :
    - [x]  Brancher l'input de recherche à MeiliSearch + response time + number of candidates
    - [x]  Liste des indexes
    - [x]  API key
    - [x]  The facets results with the facet count
    - [x]  No pagination, load more result (button)
    - [x]  liste des liens utiles (github/documentation)
- [x]  The search results, pretty view or json view with a switch (1 j)
- [x]  Other designs adjustments (1 j)
- [ ]  An optional input for manual filters (advanced mode) (pas d'estimation pour le moment)

**TODO détaillée :** 

- [x]  Stocker l'index sélectionné (ou le premier par défaut) dans le localStorage
- [x]  Tester si on supprime l'indexe mais qu'on en a un dans le localStorage
- [x]  Composant Typography
- [x]  Implémenter modale particulière si pas d'API requis
- [x]  Design de la croix dans la searchBar
- [x]  Mettre du Throttle dans la searchBar
- [x]  Implémenter le select avec le switch d'index +
- [x]  Implémenter le nombre de result par index dans le select
- [x]  Design du Select
- [x]  Implémenter le "no index found"
- [x]  Design modale (title, contenu, backdrop, close button, ...)
- [x]  Implémenter API key not valid (dans la modale)
- [x]  Design boutons ("Clear all Filters", "Show more", "API Key", "Load more", bouton toggle JSON, ...)
- [x]  IconButton: croix dans la modale, "?" Help Center
- [x]  Design Toggle Fancy/JSON
- [x]  Implémenter la vue JSON et brancher au Toggle
- [x]  Design du "Hits" et "Time Spent" (si le nbHits = nbResults alors ne pas mettre le ~)
- [x]  Design de la vue où 0 documents dans l'index
- [x]  Design de la modale "Help Center"
- [x]  Ajout du favicon
- [x]  Design vue "Welcome"
- [x]  Design "Sorry mate"
- [x]  Implémenter le "Show more" des Cards
- [x]  Implémenter la photo des Cards
- [x]  Implémenter l'affichage JSON des Cards au click sur le bouton
- [x]  Implémenter le scroll to top
- [ ]  Implémenter le loader (⚠️ blocked by Instant MeiliSearch)
- [ ]  Implémenter le crop sur les fields (⚠️ blocked by Instant MeiliSearch)
- [x]  Fixer les problèmes de design sous Firefox
- [x]  Repasser sur tous les états des boutons, inputs, etc...
- [x]  Mettre les liens en <a>
- [x]  Implémenter la croix pour clean l'input si j'ai le temps (sous Firefox)
- [x]  Readme
- [ ]  Remplacer le Dashboard actuel dans la doc : [https://docs.meilisearch.com/learn/getting_started/quick_start.html#search](https://docs.meilisearch.com/learn/getting_started/quick_start.html#search)

## Facets

- [x]  Design des checkbox
- [x]  Design de la sidebar visible / hidden
- [ ]  Stocker dans le localStorage si la modal doit être ouverte ou fermée
- [ ] Implémenter les facets de type number
- [ ] Design des facets de type number
- [x]  Implémenter les facets de type string
- [x]  Design des facets de type string

A simple interface with:

- The search bar with the response time and the numbers of candidates
- An optional input for the API Key
- The search results, pretty view or json view with a switch
- The facets results with the facet count
- An optional input for manual filters (advanced mode)
- No pagination, load more result (button)
- liste des liens utiles (github/documentation)

**Comment by qdequele** [comment]
@lpinot is the design finished?
