### ISSUE TITLE
Organize the design system

### ISSUE THREAD

**Issue by chayaline** [meilisearch/design-team#22]
# Context
The goal of a design system(DS) is to have a shared library of flexible components and tokens that we can use quickly to design new mockups, and that developers can refer to when they need it. 
It will help us design faster, maintain consistency throughout the SaaS and other projects, and simplify the developer's work.
 

# Goal
Have an exhaustive and up-to-date library of UI components.

# Ressources
[Design System file
](https://www.figma.com/file/XXmUvsZzfZBKt1i2v12wf4/Design-System?node-id=1504%3A282)

# Todo
- [x] Organize the DS according to the [atomic design methodology](https://bradfrost.com/blog/post/atomic-web-design/)
- [x] Define a naming system for the variants props with the devs
- [x] Make the existing components use the variants system
- [ ] Add missing variants to those components
- [x] create an inventory of components on Notion, that will allow us to see quickly what's missing on Figma or storybook
- [x] Add more typos for both the cloud and the website @lpinot 
- [x] Review the colors in the design system @lpinot

**Comment by qdequele** [comment]
As it will be a never-finished work, I propose to close this issue, please create new smaller issues when you have new tasks to do on the design system.
