### ISSUE TITLE
Define and display user and project slug

### ISSUE THREAD

**Issue by chayaline** [meilisearch/design-team#28]
# Context
see https://github.com/meilisearch/product/issues/406

# Tasks
- [x] add verification on username input, no spaces, only alphanumeric and hyphens
- [x] add full name => unique slug 
- [x] prefill the name input based on the email - ex: my.name@email.com => name = my-name or myname, add numbers if already used

# Deliverables
- [Register form](https://www.figma.com/file/9GA8LomQgcbKiozYhgxa0C/Cloud-Interfaces?node-id=195%3A4513)
- [Create a project modal](https://www.figma.com/file/9GA8LomQgcbKiozYhgxa0C/Cloud-Interfaces?node-id=328%3A2473)
- [Change password input hint](https://www.figma.com/file/9GA8LomQgcbKiozYhgxa0C/Cloud-Interfaces?node-id=206%3A320)

**Comment by chayaline** [comment]
Create a project: 
![Capture d’écran 2022-03-24 à 09 23 43](https://user-images.githubusercontent.com/16258667/159873390-033330d7-7a60-4269-a7f9-ffd5c0c9c4c7.png)

Register
![Capture d’écran 2022-03-23 à 09 29 37](https://user-images.githubusercontent.com/16258667/159656124-5679e0fb-7176-4668-8314-f269eab2653c.png)

Change password input hint
![Capture d’écran 2022-03-23 à 09 39 19](https://user-images.githubusercontent.com/16258667/159657965-9d1897c4-d336-47b8-9864-82aa5e5a2cd2.png)
