### ISSUE TITLE
Define how we display errors

### ISSUE THREAD

**Issue by chayaline** [meilisearch/design-team#30]
# Context
Define how and when to display each type of error and notification

# Resources
[Errors guidelines
](https://www.figma.com/file/XXmUvsZzfZBKt1i2v12wf4/Design-System?node-id=1793%3A4668)

# Tasks
- [x] define contextualized errors behavior
- [x] define global errors behavior
- [ ] define special cases
- [ ] add missing components
