### ISSUE TITLE
Billing view: improvements from testing sessions

### ISSUE THREAD

**Issue by chayaline** [meilisearch/design-team#33]
# Context
After conducting 6 user shadowing sessions, we gathered a lot of feedback about the billing view. 

# Tasks
- [x] missing explanations about why users are billed for 1hr when they used the project less than 1hr
- [x] missing explanation about what the hours count is
- [x] it's not clear that it is an estimation: add explanations and put the word estimation in emphasis
- [x] add the currency symbol on the hourly cost
- [x] use only 2 digits after coma for numbers
- [x] add the server's location in the summary
- [x] add a visual cue to tell users if they have a registered working card
- [x] add a "deleted project" indicator on the summary list

# Deliverable
- [Figma Mockups](https://www.figma.com/file/2h9RKFonJ6WElfBsRmXuqa/Billing?node-id=201%3A575)

**Comment by chayaline** [comment]
Closing after showing it to @nicolasvienot and @eskombro
