### ISSUE TITLE
Create a design testers group

### ISSUE THREAD

**Issue by chayaline** [meilisearch/design-team#37]
# Context

With a new version of the cloud and a growing number of beta testers, we can take this opportunity to start testing our designs with real users. 
For this an ideal way would be to constitute a group of users willing to help us improve the cloud's design.

# Tasks
- [ ] write NDA
- [x] collect user's agreement to participate in tests
- [ ] think about an incentive for testers
- [x] recruit users: could be slack-community cloud channel, crisp/intercom database, or random paid testers from Reach
- [x] import list on reach
- [x] define rules for sending tests (for example: no more than 1 mail per 3 weeks etc)

**Comment by chayaline** [comment]
closing because it's working ok without incentive, and we don't need an NDA
